"use strict";
const canvas=document.querySelector('#game-canvas'),ctx=canvas.getContext('2d');
const menu=document.querySelector('#menu'),hud=document.querySelector('#hud'),pausePanel=document.querySelector('#pause-panel'),endPanel=document.querySelector('#end-panel'),touch=document.querySelector('#touch-controls');
const input={left:false,right:false,jump:false,run:false,fire:false};
const game={state:'menu',level:0,camera:0,time:0,score:0,coins:0,lives:3,shake:0};
let world,player,enemies,items,particles,solids,last=0;
const W=960,H=540,gravity=.62,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const rect=(x,y,w,h)=>({x,y,w,h});
function buildLevel(index){
  const widths=[3400,3900,4500], themes=['meadow','sunset','night'], width=widths[index];
  const ground=[];for(let x=0;x<width;x+=80)ground.push(rect(x,468,80,72));
  const platforms=[];for(let x=280;x<width-180;x+=index?360:300){const y=360-(Math.floor(x/300)%3)*55;platforms.push(rect(x,y,140,18));if(x%720===0)platforms.push(rect(x+30,y-80,90,18));}
  const coinList=[];for(let x=170;x<width-100;x+=145)coinList.push({x,y:410-(Math.floor(x/145)%3)*45,taken:false});
  const itemList=[{x:420,y:320,type:'mushroom',taken:false},{x:1150,y:280,type:'flower',taken:false},{x:2050,y:300,type:'star',taken:false}];
  const foes=[];for(let x=580;x<width-170;x+=330)foes.push({x,y:430,w:32,h:38,vx:-1.2,vy:0,dead:false,type:x%660===0?'koopa':'goomba'});
  return {width,theme:themes[index],ground,platforms,coins:coinList,items:itemList,enemies:foes,flag:rect(width-130,180,32,288)};
}
function start(level=game.level,reset=true){game.level=level;world=buildLevel(level);solids=[...world.ground,...world.platforms];enemies=world.enemies.map(e=>({...e}));items=world.items.map(i=>({...i}));particles=[];game.time=0;game.camera=0;if(reset){game.score=0;game.coins=0;game.lives=3}player={x:75,y:400,w:30,h:42,vx:0,vy:0,face:1,grounded:false,power:'small',star:0,hurt:0,fire:[],walk:0};game.state='playing';menu.classList.add('hidden');endPanel.classList.add('hidden');pausePanel.classList.add('hidden');hud.classList.remove('hidden');touch.classList.remove('hidden');updateHud();}
function moveBody(body){body.x+=body.vx;for(const s of solids)if(hit(body,s)){if(body.vx>0)body.x=s.x-body.w;else if(body.vx<0)body.x=s.x+s.w;body.vx=0}body.y+=body.vy;body.grounded=false;for(const s of solids)if(hit(body,s)){if(body.vy>0){body.y=s.y-body.h;body.vy=0;body.grounded=true}else if(body.vy<0){body.y=s.y+s.h;body.vy=0}}}
function update(dt){game.time+=dt;player.hurt=Math.max(0,player.hurt-dt);player.star=Math.max(0,player.star-dt);const speed=input.run?5.8:4;
  player.vx=input.left?-speed:input.right?speed:player.vx*.76;if(player.vx)player.face=Math.sign(player.vx);if(input.jump&&!player.jumpLock&&player.grounded){player.vy=-12;player.grounded=false;beep(520,.08)}player.jumpLock=input.jump;player.vy=Math.min(14,player.vy+gravity*dt);moveBody(player);player.walk+=Math.abs(player.vx)*dt;
  if(input.fire&&player.power==='fire'&&player.fire.length<2){player.fire.push({x:player.x+player.w/2,y:player.y+20,vx:player.face*8,vy:-3,life:100});input.fire=false;beep(180,.06)}player.fire.forEach(f=>{f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=.25*dt;f.life-=dt});player.fire=player.fire.filter(f=>f.life>0&&f.x>-100&&f.x<world.width);
  enemies.forEach(e=>{if(e.dead)return;e.vy=Math.min(12,e.vy+gravity*dt);e.x+=e.vx*dt;e.y+=e.vy*dt;let floor=solids.find(s=>hit(e,s));if(floor){if(e.vy>=0){e.y=floor.y-e.h;e.vy=0}else{e.y=floor.y+floor.h;e.vy=0}}if(!solids.some(s=>e.x+e.w+e.vx> s.x&&e.x+e.vx<s.x+s.w&&e.y+e.h<=s.y+5))e.vx*=-1;if(e.x<0||e.x+e.w>world.width)e.vx*=-1;
    if(hit(player,e)&&!e.dead){if(player.vy>0&&player.y+player.h-player.vy<e.y+14){e.dead=true;player.vy=-8;game.score+=150;burst(e.x,e.y,'#ffd35a')}else if(player.star>0){e.dead=true;game.score+=200}else if(player.hurt<=0){damage()}}});
  player.fire.forEach(f=>enemies.forEach(e=>{if(!e.dead&&hit({x:f.x-7,y:f.y-7,w:14,h:14},e)){e.dead=true;f.life=0;game.score+=200;burst(e.x,e.y,'#ff7043')}}));
  world.coins.forEach(c=>{if(!c.taken&&hit(player,{x:c.x,y:c.y,w:18,h:25})){c.taken=true;game.coins++;game.score+=50;beep(880,.06);burst(c.x,c.y,'#ffe06a')}});items.forEach(i=>{if(!i.taken&&hit(player,{x:i.x,y:i.y,w:30,h:30})){i.taken=true;if(i.type==='star')player.star=600;else player.power=i.type==='flower'?'fire':'big';game.score+=500;beep(660,.16)}});
  if(player.y>H+80){damage(true)}if(hit(player,world.flag))finish();game.camera=clamp(player.x-300,0,world.width-W);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);game.shake=Math.max(0,game.shake-dt);updateHud();}
function damage(fall=false){if(player.star>0)return;if(player.hurt>0&&!fall)return;if(player.power!=='small'&&!fall){player.power='small';player.hurt=100;player.vx=-player.face*4;beep(130,.12);return}game.lives--;game.shake=12;if(game.lives<=0){game.state='gameover';showEnd('FIM DE JOGO','A aventura termina aqui.')}else{player.x=75;player.y=350;player.vx=0;player.vy=0;player.hurt=130}}
function finish(){if(game.state!=='playing')return;game.score+=1000;if(game.level<2){start(game.level+1,false)}else{game.state='victory';showEnd('VITÓRIA!','Você atravessou os três mundos.')}}
function showEnd(title,text){document.querySelector('#end-title').textContent=title;document.querySelector('#end-text').textContent=`${text} Pontuação: ${game.score}`;document.querySelector('#end-kicker').textContent=game.state==='victory'?'JORNADA CONCLUÍDA':'TENTE NOVAMENTE';document.querySelector('#end-button').textContent=game.state==='victory'?'Jogar de novo':'Tentar novamente';hud.classList.add('hidden');touch.classList.add('hidden');endPanel.classList.remove('hidden')}
function updateHud(){document.querySelector('#level-value').textContent=`${game.level+1}/3`;document.querySelector('#lives-value').textContent=game.lives;document.querySelector('#coins-value').textContent=game.coins;document.querySelector('#score-value').textContent=game.score}
function burst(x,y,color){for(let i=0;i<8;i++)particles.push({x,y,vx:(Math.random()-.5)*4,vy:(Math.random()-.8)*4,life:30,color})}
function draw(){ctx.save();if(game.shake)ctx.translate((Math.random()-.5)*game.shake,(Math.random()-.5)*game.shake);const night=world?.theme==='night',g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,night?'#172044':world?.theme==='sunset'?'#e87867':'#4db9d8');g.addColorStop(1,night?'#4a3561':world?.theme==='sunset'?'#f8b36b':'#c5efd9');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  ctx.save();ctx.translate(-game.camera*.18,0);ctx.fillStyle=night?'#7d83bf':'#ffffff55';for(let i=0;i<10;i++){const x=i*180+80,y=90+(i%3)*45;ctx.beginPath();ctx.arc(x,y,30,Math.PI,0);ctx.arc(x+35,y,38,Math.PI,0);ctx.arc(x+78,y,25,Math.PI,0);ctx.fill()}ctx.fillStyle=night?'#f8df8c':'#ffd35a';ctx.beginPath();ctx.arc(790,95,night?24:38,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(-game.camera,0);
  ctx.fillStyle='#2d7e66';for(const s of solids){ctx.fillStyle=s.h<30?'#3d9d70':'#70442f';ctx.fillRect(s.x,s.y,s.w,s.h);ctx.fillStyle=s.h<30?'#7bdc78':'#45aa63';ctx.fillRect(s.x,s.y,s.w,7)}
  world.coins.forEach(c=>{if(c.taken)return;const bob=Math.sin(game.time*.1+c.x)*3;ctx.fillStyle='#ffd452';ctx.strokeStyle='#b87522';ctx.beginPath();ctx.ellipse(c.x+9,c.y+12+bob,7,12,0,0,Math.PI*2);ctx.fill();ctx.stroke()});items.forEach(i=>{if(i.taken)return;ctx.fillStyle=i.type==='star'?'#ffe253':i.type==='flower'?'#ff5d6c':'#e84e48';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=14;ctx.beginPath();ctx.arc(i.x+15,i.y+15+Math.sin(game.time*.08+i.x)*3,15,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});
  const f=world.flag;ctx.fillStyle='#e9eef0';ctx.fillRect(f.x,f.y,6,f.h);ctx.fillStyle='#ff5b65';ctx.fillRect(f.x+6,f.y,55,32);enemies.forEach(e=>{if(e.dead)return;ctx.fillStyle=e.type==='koopa'?'#2eae66':'#a85535';ctx.beginPath();ctx.arc(e.x+16,e.y+15,16,Math.PI,0);ctx.fill();ctx.fillRect(e.x+2,e.y+15,28,15);ctx.fillStyle='#fff';ctx.fillRect(e.x+7,e.y+8,6,8);ctx.fillRect(e.x+19,e.y+8,6,8);ctx.fillStyle='#172044';ctx.fillRect(e.x+9,e.y+11,3,5);ctx.fillRect(e.x+20,e.y+11,3,5)});player.fire.forEach(f=>{ctx.fillStyle='#ff7043';ctx.beginPath();ctx.arc(f.x,f.y,7,0,Math.PI*2);ctx.fill()});if(!(player.hurt>0&&Math.floor(player.hurt/8)%2)){ctx.fillStyle=player.power==='fire'?'#f3e36b':'#e74752';ctx.fillRect(player.x+4,player.y+12,22,25);ctx.fillStyle='#f0b27d';ctx.beginPath();ctx.arc(player.x+15,player.y+10,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e74752';ctx.fillRect(player.x+2,player.y+1,26,7);ctx.fillStyle='#34223c';ctx.fillRect(player.x+5,player.y+37,9,5);ctx.fillRect(player.x+18,player.y+37,9,5);if(player.star>0){ctx.strokeStyle='#fff09a';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.x+15,player.y+20,25+Math.sin(game.time*.2)*3,0,Math.PI*2);ctx.stroke()}}
  particles.forEach(p=>{ctx.globalAlpha=p.life/30;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5)});ctx.restore();ctx.restore()}
function beep(freq,dur){try{const a=new AudioContext(),o=a.createOscillator(),v=a.createGain();o.frequency.value=freq;o.type='square';v.gain.value=.04;o.connect(v);v.connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch(e){}}
function frame(t){const dt=Math.min(2,(t-last)/16.67||1);last=t;if(game.state==='playing')update(dt);draw();requestAnimationFrame(frame)}
function key(name,value){input[name]=value}addEventListener('keydown',e=>{if(e.key==='Enter'&&game.state==='menu')start();if(e.key==='p'||e.key==='Escape')togglePause();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')key('left',true);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')key('right',true);if(e.key==='ArrowUp'||e.key.toLowerCase()==='w'||e.key===' ')key('jump',true);if(e.key==='Shift')key('run',true);if(e.key.toLowerCase()==='x')key('fire',true);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')key('left',false);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')key('right',false);if(e.key==='ArrowUp'||e.key.toLowerCase()==='w'||e.key===' ')key('jump',false);if(e.key==='Shift')key('run',false);if(e.key.toLowerCase()==='x')key('fire',false)});
function togglePause(){if(game.state==='playing'){game.state='paused';pausePanel.classList.remove('hidden')}else if(game.state==='paused'){game.state='playing';pausePanel.classList.add('hidden')}}document.querySelector('#start-button').onclick=()=>start();document.querySelector('#resume-button').onclick=togglePause;document.querySelector('#pause-button').onclick=togglePause;document.querySelector('#menu-button').onclick=()=>{game.state='menu';pausePanel.classList.add('hidden');hud.classList.add('hidden');menu.classList.remove('hidden')};document.querySelector('#end-button').onclick=()=>start(0,true);document.querySelector('#end-menu-button').onclick=()=>{game.state='menu';endPanel.classList.add('hidden');menu.classList.remove('hidden')};document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();key(k,true)});['pointerup','pointercancel','pointerleave'].forEach(type=>b.addEventListener(type,()=>key(k,false)))});addEventListener('resize',()=>{const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0)});dispatchEvent(new Event('resize'));start(0,true);game.state='menu';menu.classList.remove('hidden');hud.classList.add('hidden');touch.classList.add('hidden');requestAnimationFrame(frame);
